AllCops:
  Exclude:
    - "Gemfile"
    - "*.gemspec"
    - "spec/spec_helper"
    - "lib/trello/tools/version.rb"
    - "bin/*.*"
    - "Rakefile"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - "lib/trello/snapshot/models/action.rb"
