name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        ruby: ['2.4', '2.5', '2.6', '2.7']
    name: Ruby ${{matrix.ruby}} on ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
      env:
        TRELLO_KEY: 42
        TRELLO_TOKEN: 42
        BOARD_ID: 42
    - name: Run quality checks
      run: bundle exec rubocop
